# Generated by Django 5.2.3 on 2025-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_teacher",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                max_length=10,
            ),
        ),
    ]
