# Generated by Django 5.2.3 on 2025-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_classroom_alter_studentprofile_grade_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="enrollment_number",
            field=models.CharField(max_length=20),
        ),
    ]
