# Generated by Django 5.2.3 on 2025-06-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_studentassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="total_marks",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="studentassignment",
            name="status",
            field=models.CharField(
                choices=[("submitted", "Submitted"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentassignment",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
